name: flutter_community_challenges
description: A Flutter application to manage community driven Flutter development challenges

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  groovin_material_icons: ^1.0.2
  groovin_widgets: ^1.1.0
  rounded_modal: ^1.0.0
  outline_material_icons: ^0.1.0
  dynamic_theme: ^1.0.0
  simple_auth_flutter: ^2.0.0
  firebase_auth: ^0.6.5
  cloud_firestore: ^0.8.2+3
  firebase_core: ^0.2.5+1
  package_info: ^0.3.2
  image_picker: ^0.4.10
  yaml: ^2.1.15
  flutter_slidable: "^0.4.9"

dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  assets:
    - images/flutt.png
    - properties/properties.yaml

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
